export const EXTERNAL_METHOD_NAMES = {
  SET_DATA: 'set_data',
  GET_DATA: 'get_data',
  AGGREGATE_COLUMNS: 'aggregate_columns',
  CONCATENATED_VALUES: 'concatenated_values',
  GET_HIERARCHY: 'get_hierarchy',
  GROUP_CATEGORIES: 'group_categories',
  GROUPED_COLUMNS: 'grouped_columns',
  HISTOGRAM_VALUES: 'histogram_values',
  SINGLE_STACK_BAR_VALUES: 'single_stack_bar_values',
  STACK_CATEGORY_TOTALS: 'stack_category_totals',
  STACKED_BAR_CATEGORIES: 'stacked_bar_categories',
  STACKED_GROUP_CATEGORIES: 'stacked_group_categories',
  STACKED_GROUP_CATEGORIES_ALT: 'stacked_group_categories_alt',
  STACKED_GROUP_CATEGORIES_ALT_2: 'stacked_group_categories_alt_2',
  TIMELINE_VALUES: 'timeline_values',
  GET_CONNECTED_DOT_SERVICES: 'get_connected_dot_services',
};
